on: [push, pull_request]
name: Run Acceptance Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Tests
      run: go test ./...
      shell: bash
      env:
        GITHUB_USERNAME: gwm-testing
        GITHUB_PASSWORD: ${{ secrets.GITHUB_PASSWORD }} 
        